import "@/styles/globals.css"
import { UserProvider } from "./usercontext"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
      <body>{children}</body>
      </UserProvider>
    </html>
  )
}
